Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine310"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    apk add libc6-compat util-linux
  SHELL
  config.vm.provision :shell, run: 'always', inline: <<-SHELL
	umount /vagrant
	/sbin/mount.vboxsf -o uid=1000 -o gid=1000 vagrant /vagrant
	chmod go+rx /vagrant
  SHELL
end
